-- STRONG GIRL BATTLE — SUPABASE SETUP
-- 1. Create a free project at https://supabase.com
-- 2. Open SQL Editor and run everything below.
-- 3. Copy your Project URL + anon/public key into the app's ⚙︎ menu.
--
-- IMPORTANT: This setup is intentionally simple for a private two-person app.
-- It uses the public anon role. Do not store sensitive/private information here.
-- The app only stores workout entries (person, exercise, weight, sets, reps).

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  person text not null check (person in ('julia','jana')),
  exercise text not null,
  weight numeric not null check (weight >= 0),
  sets integer not null check (sets > 0),
  reps integer not null check (reps > 0),
  created_at timestamptz not null default now()
);

alter table public.workout_logs enable row level security;

create policy "battleboard read"
on public.workout_logs for select
to anon
using (true);

create policy "battleboard insert"
on public.workout_logs for insert
to anon
with check (person in ('julia','jana') and weight >= 0 and sets > 0 and reps > 0);

-- If you already created policies with these names, delete them before rerunning:
-- drop policy if exists "battleboard read" on public.workout_logs;
-- drop policy if exists "battleboard insert" on public.workout_logs;


-- Needed for editing and deleting entries from the shared tracker
create policy "battleboard update"
on public.workout_logs for update
to anon
using (true)
with check (person in ('julia','jana') and weight >= 0 and sets > 0 and reps > 0);

create policy "battleboard delete"
on public.workout_logs for delete
to anon
using (true);
